config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :stations, only: [:index, :show]
  resources :stations, only: [:index, :show] do
    resources :platforms
    member do
        get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coinlocker.rb
class Coinlocker < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '進行方向 前' },
    { id: 2, name: '中央' },
    { id: 3, name: '進行方向 後' },
    { id: 4, name: '進行方向 前・中央' },
    { id: 5, name: '進行方向 前・進行方向 後' },
    { id: 6, name: '中央・進行方向 後' },
    { id: 7, name: '進行方向 前・中央・進行方向 後' }
  ]

  include ActiveHash::Associations
  has_many :platforms

end

app/models/elevator.rb
class Elevator < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '進行方向 前' },
    { id: 2, name: '中央' },
    { id: 3, name: '進行方向 後' },
    { id: 4, name: '進行方向 前・中央' },
    { id: 5, name: '進行方向 前・進行方向 後' },
    { id: 6, name: '中央・進行方向 後' },
    { id: 7, name: '進行方向 前・中央・進行方向 後' }
  ]

  include ActiveHash::Associations
  has_many :platforms

end

app/models/escalator.rb
class Escalator < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '進行方向 前' },
    { id: 2, name: '中央' },
    { id: 3, name: '進行方向 後' },
    { id: 4, name: '進行方向 前・中央' },
    { id: 5, name: '進行方向 前・進行方向 後' },
    { id: 6, name: '中央・進行方向 後' },
    { id: 7, name: '進行方向 前・中央・進行方向 後' }
  ]

  include ActiveHash::Associations
  has_many :platforms

end

app/models/platform.rb
class Platform < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :elevator
  belongs_to_active_hash :escalator
  belongs_to_active_hash :toilet
  belongs_to_active_hash :coinlocker
  belongs_to :station
end

app/models/station.rb
class Station < ApplicationRecord
  has_many :platforms
  has_one_attached :image
end

app/models/toilet.rb
class Toilet < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '進行方向 前' },
    { id: 2, name: '中央' },
    { id: 3, name: '進行方向 後' },
    { id: 4, name: '進行方向 前・中央' },
    { id: 5, name: '進行方向 前・進行方向 後' },
    { id: 6, name: '中央・進行方向 後' },
    { id: 7, name: '進行方向 前・中央・進行方向 後' }
  ]

  include ActiveHash::Associations
  has_many :platforms

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top;end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  def index
    @stations = Station.all
  end

  def show
    @station = Station.find(params[:id])
    if params[:platform_id].present?
      @platform = @station.platforms.find_by(form: params[:platform_id])
    else
      @platform = nil
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/homes/top.html.erb
<div class="home">
  <div class="header-center">
    <div class="header-center-top">Platform Guide</div>
    <div class="header-center-bottom">
      <p>降りるフォームの番号を入力して簡単にフォーム案内が検索できるサイトです。<br >
        降りるフォームの番号を入力して簡単に検索ましょう！
      </p>
    </div>
    <div class="wrap">
      <a href="stations#index" class="button">Click me!</a>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PfGuideApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header-app-title">Platform Guide</div>
    </header>
    <%= yield %>
    <footer>
      Copyright©︎2020 Platform Guide.com, All Rights Reserved.
    </footer>
  </body>
</html>

app/views/stations/index.html.erb
<div class="main">
  <div class="content">
    <div class="content-image">
      <%= image_tag "1883714_s.jpg", class: "content-image-1" %>
      <%= image_tag "photo0000-5301.jpg", class: "content-image-2" %>
    </div>
    <div class="item-info">
    <% @stations.each do |station| %>
      <div class="item-list">
      <%= link_to station_path(station.id), method: :get do %>
      <% if station.image.attached? %>
      <%= image_tag station.image.variant(resize:'300x275') %>
      <% end %>
        <h3 class='item-name'>
          <%= station.name %>
        </h3>
      <% end %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/stations/search.html.erb
<div class="station-show">
  <div class="station-box">
    <div class="station-name">
      <p><%#= @station.name %>駅
      </p>
    </div>
    <div class="station-form">
  <% @platform.each do |platform| %>
    <%= render partial: "stations", locals: { stations: stations } %>
  <% end %>
    </div>
    <div class="wrap">
      <a href="stations#index" class="button">Click me!</a>
    </div>
  </div>
</div>

app/views/stations/show.html.erb
<div class="station-show">
  <div class="station-box">
    <div class="station-name">
      <p><%= @station.name %>駅
      </p>
    </div>
    <div class="station-form">
    <%= form_with url: station_path(@station), local: true, method: :get do |f| %>
      <div>
        <div><%= f.label :platform_id, "プラットフォーム番号" %></div>
        <div><%= f.search_field :platform_id %></div>
      </div>
      <%= f.submit class: 'search-q-btn' %>
    <% end %>
    <%if false %>
    <%= search_form_for @q, url: root_path do |f| %>
      <div>
        <div><%= f.label :user_name_cont, "ユーザー名" %></div>
        <div><%= f.search_field :user_name_cont %></div>
      </div>
      <%= f.submit class: 'search-q-btn' %>
      <% end %>
    <% end %>
    </div>
    <% if @platform %>
    <%= @platform.elevator.name %>
    <% end %>
    <div class="wrap">
      <a href="stations#index" class="button">Click me!</a>
    </div>
  </div>
</div>